// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8PmJupuf8fYNsGhWvGdl4I1iv6GQyBxU',
    appId: '1:435178411449:web:f4e6d24320a00874f7d268',
    messagingSenderId: '435178411449',
    projectId: 'billimiut',
    authDomain: 'billimiut.firebaseapp.com',
    databaseURL: 'https://billimiut-default-rtdb.firebaseio.com',
    storageBucket: 'billimiut.appspot.com',
    measurementId: 'G-7CT3PPYJ2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNm7RwvQ1N34q--C4z4OplT7W9C616CQ8',
    appId: '1:435178411449:android:13178719782f398af7d268',
    messagingSenderId: '435178411449',
    projectId: 'billimiut',
    databaseURL: 'https://billimiut-default-rtdb.firebaseio.com',
    storageBucket: 'billimiut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6lzIZAxE2yOZWuNOV5hcveEg4DAEP3mc',
    appId: '1:435178411449:ios:a11db617bb5aa8dcf7d268',
    messagingSenderId: '435178411449',
    projectId: 'billimiut',
    databaseURL: 'https://billimiut-default-rtdb.firebaseio.com',
    storageBucket: 'billimiut.appspot.com',
    iosBundleId: 'com.example.billimiutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6lzIZAxE2yOZWuNOV5hcveEg4DAEP3mc',
    appId: '1:435178411449:ios:175b6e9d38190c97f7d268',
    messagingSenderId: '435178411449',
    projectId: 'billimiut',
    databaseURL: 'https://billimiut-default-rtdb.firebaseio.com',
    storageBucket: 'billimiut.appspot.com',
    iosBundleId: 'com.example.billimiutApp.RunnerTests',
  );
}
